### PR TITLE
CEENG-173

### PR DESCRIPTION
**Pull request by nikitasheremet**
Converted files to typescript as per CEENG-173 ticket. Some questions in the comments in the format "//PR".

### CODE REVIEW

**Review by junzhengca — CHANGES_REQUESTED** [review]
Impossible to review. What is this? And can you split it into smaller PRs?

**Comment by nikitasheremet** [comment]
@junthehacker In my conversation with Ralph, I understood that you were aware of this ticket. As per the ticket, he asked me to migrate the SDK files to typescript. I did not touch any of the logic just added types. The reason I submitted everything in one PR is that all the changes fell under the scope of the issued ticket. I can resubmit as multiple PRs, but could you specify how you would like me to split up the PRs?

**Comment by junzhengca** [comment]
Add build configurations for ts first. And slowly migrate each file into typescript. Try to maintain your PR less than 500 lines, at most 1000.

**Comment by bholagabbar** [comment]
@nikitasheremet Sorry, but I will be closing this PR again. We maintain JS SDK and we are not even remotely aware of what is going on. If you want a typescript SDK, make a new repository. Additionally, I don't understand how moving to typescript is going to help you when your applications themselves are in JS SDK.

**Comment by bholagabbar** [comment]
@nikitasheremet Please setup a meeting with ralph, jun yourself and I and we can discuss the requirements and make a plan.

**Comment by ralph-dev** [comment]
Do not make any further modifications to the SDK / This Branch / PR. We will jump on a call all together to move forward. This is time sink for any further modifications. Park this on the side until future conversations.

**Pull request closed without merging**
